- name: Git pull
  git:
    accept_hostkey: true
    dest: '{{ project_folder }}'
    clone: true
    force: yes
    update: yes
    repo: '{{ repo }}'
    version: vagrant

- name: Copy parameter.yml
  copy:
    src: '{{ project_folder }}/app/config/parameters.yml.dist'
    remote_src: yes
    dest: '{{ project_folder }}/app/config/parameters.yml'
    force: no

- name: Copy maxibooking.env
  copy:
    src: '{{ project_folder }}/app/config/clients/maxibooking.env.dist'
    remote_src: yes
    dest: '{{ project_folder }}/app/config/clients/maxibooking.env'
    force: no

- name: Copy database.env
  copy:
    src:  '{{ project_folder }}/app/config/database.env.dist'
    remote_src: yes
    dest: '{{ project_folder }}/app/config/database.env'
    force: no

- name: Copy secrets.env
  copy:
    src:  '{{ project_folder }}/app/config/secrets.yml.dist'
    remote_src: yes
    dest: '{{ project_folder }}/app/config/secrets.yml'
    force: no

- name: Composer install
  composer:
    command: install
    working_dir: '{{ project_folder }}'
    optimize_autoloader: no
