# Значения справочника см. в каталоге DOC\Справочники\ файл dict_s_docum.csv.
docum:
  vega_residence: 'vega_residence'
  vega_visa: 'vega_visa'
  vega_military_spare: 'vega_military_spare'
  vega_temporary_identity: 'vega_temporary_identity'
  vega_diplomatic_passport: 'vega_diplomatic_passport'
  vega_travel_passport: 'vega_travel_passport'
  vega_russian_passport: 'vega_russian_passport'
  vega_ussr_passports: 'vega_ussr_passports'
  vega_passport_foreigner: 'vega_passport_foreigner'
  vega_seaman: 'vega_seaman'
  vega_temporary_residence_permit_foreigner: 'vega_temporary_residence_permit_foreigner'
  vega_predost_temporate_asylum: 'vega_predost_temporate_asylum'
  vega_refugee: 'vega_refugee'
  vega_birth_certificate: 'vega_birth_certificate'
  vega_st_of_birth_foreigner: 'vega_st_of_birth_foreigner'
  vega_service_passports: 'vega_service_passports'
  vega_refugee_certificate: 'vega_refugee_certificate'
  vega_id_card_person_of_military: 'vega_id_card_person_of_military'
  vega_residence_permit_stateless_persons: 'vega_residence_permit_stateless_persons'
  vega_military_id_soldier: 'vega_military_id_soldier'
  vega_travel_passport_biometrics: 'vega_travel_passport_biometrics'
  vega_temporary_residence_permit_stateless_persons: 'vega_temporary_residence_permit_stateless_persons'
  vega_migration_cart: 'vega_migration_cart'
  vega_foreigner_arrival_notice:  'vega_foreigner_arrival_notice'
  vega_return_certificate: 'vega_return_certificate'
  vega_non_citizen_passport: 'vega_non_citizen_passport'
  vega_national_id_republic_of_kazakhstan: 'vega_national_id_republic_of_kazakhstan'
