housepart:
  house: 'housepart.house'
  litera_house: 'housepart.litera_house'
  flat: 'housepart.flat'
  litera_flat: 'housepart.litera_flat'
  corpus: 'housepart.corpus'
  construction: 'housepart.construction'
  structure: 'housepart.structure'
  building: 'housepart.building'
