tpscan:
  notify_front: 'tpscan.notify_front'
  notify_back: 'tpscan.notify_back'
  document: 'tpscan.document'
  visa: 'tpscan.visa'
  residence_ig: 'tpscan.residence_ig'
  residence_lbg: 'tpscan.residence_lbg'
  temporary_accommodation_ig: 'tpscan.temporary_accommodation_ig'
  temporary_accommodation_lbg: 'tpscan.temporary_accommodation_lbg'
  migration_card: 'tpscan.migration_card'
