---

- name: Apache encode example
  hosts: all
  vars_files:
    - vars/apache_test.yaml
  tasks:
    - name: Create test.apache file
      template:
        src: templates/test.apache.j2
        dest: /tmp/test.apache
      tags:
        - apache

- name: Erlang encode example
  hosts: all
  vars_files:
    - vars/erlang_test.yaml
  tasks:
    - name: Create test.erlang file
      template:
        src: templates/test.erlang.j2
        dest: /tmp/test.erlang
      tags:
        - erlang

- name: INI encode example
  hosts: all
  vars_files:
    - vars/ini_test.yaml
  tasks:
    - name: Create test.ini file
      template:
        src: templates/test.ini.j2
        dest: /tmp/test.ini
      tags:
        - ini

- name: Simplified INI encode example
  hosts: all
  vars_files:
    - vars/ini_test.yaml
  tasks:
    - name: Create test.simple file
      template:
        src: templates/test.ini_simple.j2
        dest: /tmp/test.ini_simple
      tags:
        - simple

- name: JSON encode example
  hosts: all
  vars_files:
    - vars/json_test.yaml
  tasks:
    - name: Create test.json file
      template:
        src: templates/test.json.j2
        dest: /tmp/test.json
      tags:
        - json

- name: Logstash encode example
  hosts: all
  vars_files:
    - vars/logstash_test.yaml
  tasks:
    - name: Create test.logstash file
      template:
        src: templates/test.logstash.j2
        dest: /tmp/test.logstash
      tags:
        - logstash

- name: TOML encode example
  hosts: all
  vars_files:
    - vars/toml_test.yaml
  tasks:
    - name: Create test.toml file
      template:
        src: templates/test.toml.j2
        dest: /tmp/test.toml
      tags:
        - toml

- name: XML encode example
  hosts: all
  vars_files:
    - vars/xml_test.yaml
  tasks:
    - name: Create test.xml file
      template:
        src: templates/test.xml.j2
        dest: /tmp/test.xml
      tags:
        - xml

- name: YAML encode example
  hosts: all
  vars_files:
    - vars/yaml_test.yaml
  tasks:
    - name: Create test.yaml file
      template:
        src: templates/test.yaml.j2
        dest: /tmp/test.yaml
      tags:
        - yaml
