###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.5"
services:

    memcached:
      image: memcached:alpine
      container_name: mbh-memcached2
      hostname: memcache
      networks:
        - mynetwork


    redis:
      image: redis:alpine
      container_name: mbh-redis2
      hostname: docker-redis
      networks:
        - mynetwork

    rabbitmq:
      image: rabbitmq:latest
      container_name: mbh-rabbitmq2
      hostname: docker-rabbit
      environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"
      ports:
        - "15673:15672"
        - "5673:5672"
      volumes:
        - ./phpdocker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      networks:
        - mynetwork

    mongo:
      image: mongo:3.4
      container_name: mbh-mongo2
      hostname: docker-mongo
      command: mongod --setParameter failIndexKeyTooLong=false
      volumes:
        - mongo_data2:/data/db
      ports:
        - "27018:27017"
      networks:
        - mynetwork

    webserver:
      image: nginx:alpine
      container_name: mbh-webserver2
      hostname: docker-webserver
      working_dir: /var/www/mbh
      volumes:
        - ..:/var/www/mbh
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "9090:80"
      networks:
        - mynetwork

    php-fpm:
      build: phpdocker/php-fpm
      container_name: mbh-php-fpm2
      hostname: docker-php-fpm
      working_dir: /var/www/mbh
      volumes:
        - ..:/var/www/mbh
        - ./phpdocker/php-fpm/php-ini-overrides-fpm.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
        - ./phpdocker/php-fpm/php-ini-overrides-cli.ini:/etc/php/7.1/cli/conf.d/99-overrides.ini
        - ./phpdocker/php-fpm/start.sh:/start.sh
        - ./phpdocker/php-fpm/fish:/root/.config/fish/functions
        - /tmp/:/tmp/
      networks:
        - mynetwork
      dns:
          - 8.8.8.8

volumes:
  mongo_data2:
    driver: local

networks:
  mynetwork:
    name: mbh-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
