services:
    mbh.mbhs:
        class: MBH\Bundle\ClientBundle\Service\Mbhs
        arguments: ['@service_container']
    mbh.notice.unpaid:
        class: MBH\Bundle\ClientBundle\Service\NoticeUnpaid
        arguments: ['@service_container','@doctrine_mongodb', '@mbh.notifier.mailer']

    mbh.package_moving:
          class: MBH\Bundle\ClientBundle\Service\PackageMoving
          arguments:
              - '@doctrine.odm.mongodb.document_manager'
              - '@service_container'
              - '@validator'
              - '@mbh.package_zip.logger'
              - '@mbh.order_manager'
              - '@mbh.package.search'
              - '@mbh.helper'

    mbh.package_zip.logger:
          class:     Symfony\Bridge\Monolog\Logger
          arguments: [app]
          calls:
              - [pushHandler, ['@mbh.package_zip.logger_handler']]

    mbh.package_zip.logger_handler:
          class:     Monolog\Handler\StreamHandler
          arguments: [%kernel.logs_dir%/%kernel.environment%.packageZip.log, 200]

    mbh.client_payment_system_type:
        class: MBH\Bundle\ClientBundle\Form\ClientPaymentSystemType
        arguments:
            - '%mbh.payment_systems%'
            - '%mbh.payment_systems.change%'
            - '%mbh.payment_systems.default%'
            - '%mbh.taxation%'
        tags:
            - { name: form.type }

    mbh.new_rbk_create_invoice.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, ['@mbh.new_rbk_create_invoice.logger_handler']]

    mbh.new_rbk_create_invoice.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: ["%kernel.logs_dir%/%kernel.environment%.paymentSystem_newRbk.log", 200]

    mbh.new_rbk_invoice_create:
        class: MBH\Bundle\ClientBundle\Service\PaymentSystem\NewRbkInvoiceCreate
        arguments: ['@service_container']