parameters:
    log_file.documents_template: !php/const:MBH\Bundle\ClientBundle\Command\DocumentTemplateUpdateCommand::FILE_LOG_NAME

services:
    mbh.mbhs:
        class: MBH\Bundle\ClientBundle\Service\Mbhs
        arguments: ['@service_container']
    mbh.notice.unpaid:
        class: MBH\Bundle\ClientBundle\Service\NoticeUnpaid
        arguments: ['@service_container','@doctrine_mongodb', '@mbh.notifier.mailer']
        
    #Dashboard
    mbh.dashboard:
      class: MBH\Bundle\ClientBundle\Service\Dashboard\Dashboard
      calls:
        - [attach, ["@mbh.dashboard.room_cache"]]
        - [attach, ["@mbh.dashboard.price_cache"]]
        - [attach, ["@mbh.dashboard.limits"]]
        - [attach, ["@mbh.dashboard.program_not_paid_source"]]
      arguments: ['@doctrine_mongodb']

    mbh.dashboard.price_cache:
      class: MBH\Bundle\ClientBundle\Service\Dashboard\PriceCacheSource
      arguments: ['@doctrine_mongodb', '@validator', '@translator', '@mbh.helper']

    mbh.dashboard.room_cache:
      class: MBH\Bundle\ClientBundle\Service\Dashboard\RoomCacheSource
      arguments: ['@doctrine_mongodb', '@validator', '@translator', '@mbh.helper']

    mbh.dashboard.limits:
        class: MBH\Bundle\ClientBundle\Service\Dashboard\LimitsDashboardSource
        arguments:
            - '@doctrine_mongodb'
            - '@validator'
            - '@translator'
            - '@mbh.helper'
            - '@mbh.client_manager'
            - '@router'

    mbh.dashboard.program_not_paid_source:
        class: MBH\Bundle\ClientBundle\Service\Dashboard\ProgramNotPaidSource
        arguments:
            - '@doctrine_mongodb'
            - '@validator'
            - '@translator'
            - '@mbh.helper'
            - '@mbh.client_manager'
            - '@router'

    mbh_bundle_client.twig.dashboard_extension:
        class: MBH\Bundle\ClientBundle\Twig\DashboardExtension
        arguments: ['@mbh.dashboard']
        tags:
            - { name: twig.extension }

    mbh.client_manager:
        class: MBH\Bundle\ClientBundle\Service\ClientManager
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - '@session'
            - '@mbh.billing.api'
            - '@mbh.billing.logger'
            - '%client%'
            - '@kernel'
            - '@mbh.client_config_manager'
            - '@mbh.helper'
    mbh.client_payment_system_type:
        class: MBH\Bundle\ClientBundle\Form\ClientPaymentSystemType
        arguments:
            - '@mbh.payment_extra_data'
        tags:
            - { name: form.type }

    mbh.client_config_type:
        class: MBH\Bundle\ClientBundle\Form\ClientConfigType
        arguments: ['@mbh.helper', '%mbh.currency.data%', '@mbh.client_manager', '%router.request_context.scheme%', '%domain%', '@translator', '@router']
        tags:
            - {name: form.type}

    mbh.template_formatter:
        class: MBH\Bundle\ClientBundle\Service\TemplateFormatter
        arguments: ['@service_container']

    mbh.fms_dictionaries:
        class: MBH\Bundle\ClientBundle\Lib\FMSDictionaries
        arguments: ['@mbh.csv_reader', '@translator']

    mbh.client_config_manager:
        class: MBH\Bundle\ClientBundle\Service\ClientConfigManager
        arguments: ['@doctrine.odm.mongodb.document_manager']

    MBH\Bundle\ClientBundle\Service\DocumentSerialize\:
        resource: '%kernel.root_dir%/../src/MBH/Bundle/ClientBundle/Service/DocumentSerialize/*'
        arguments:
             - '@service_container'
             - '@mbh.billing.api'

    MBH\Bundle\ClientBundle\Service\PaymentSystem\:
        resource: '%kernel.root_dir%/../src/MBH/Bundle/ClientBundle/Service/PaymentSystem/*'
        arguments:
            - '@service_container'

    MBH\Bundle\ClientBundle\Service\PaymentSystem\Wrapper\:
        resource: '%kernel.root_dir%/../src/MBH/Bundle/ClientBundle/Service/PaymentSystem/Wrapper/*'
        arguments:
            - '@service_container'

    mbh.document_template.logger:
          class:     Symfony\Bridge\Monolog\Logger
          arguments: [app]
          calls:
              - [pushHandler, ['@mbh.document_template.logger_handler']]

    mbh.document_template.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments:
            - "%kernel.logs_dir%/%kernel.environment%.%log_file.documents_template%"
            - 200

    mbh.payment_tinkoff.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
        - [pushHandler, ['@mbh.payment_tinkoff.logger_handler']]

    mbh.payment_tinkoff.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: ["%kernel.logs_dir%/%kernel.environment%.paymentSystem_tinkoff.log", 200]

    mbh.payment_extra_data:
        class: MBH\Bundle\ClientBundle\Lib\PaymentSystem\ExtraData
        arguments:
        - '%mbh.payment_systems%'
        - '%mbh.payment_systems.change%'
        - '%mbh.payment_systems.default%'
        - '%mbh.taxation%'

    MBH\Bundle\ClientBundle\Form\PaymentSystem\:
        resource: '%kernel.root_dir%/../src/MBH/Bundle/ClientBundle/Form/PaymentSystem/*'
        arguments:
            - '@mbh.payment_extra_data'
            - '@mbh.client_config_manager'
        tags:
        - { name: form.type }

    mbh.payment_sberbank.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
        - [pushHandler, ['@mbh.payment_sberbank.logger_handler']]

    mbh.payment_sberbank.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: ["%kernel.logs_dir%/%kernel.environment%.paymentSystem_sberbank.log", 200]
