imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.php_bridge
    profiler:
        enabled: true

swiftmailer:
    disable_delivery: true

parameters:
    mbh.mongodb:
          url: "mongodb://%mongodb_host%/%mongodb_database%%mongodb_options%"
          db : "%mongodb_database%"

security:
    firewalls:
        main:
            http_basic: ~
            form_login: false
            remember_me: false

liip_functional_test:
  authentication:
    username: "admin"
    password: "admin"

doctrine_mongodb:
    connections:
        default:
            server: "mongodb://%mongodb_host%/%mongodb_database%%mongodb_options%"