imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.php_bridge
    profiler:
        enabled: true

swiftmailer:
    disable_delivery: true

parameters:
    mongodb_url: 'mongodb://mbh-mongo:27017/test'
    mongodb_database: test

security:
    firewalls:
        main:
            http_basic: ~
            form_login: false
            remember_me: false

liip_functional_test:
  authentication:
    username: "admin"
    password: "admin"