imports:
    - { resource: config.yml }
    - { resource: mbh_dev.yml }


framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: false
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: "%debug_toolbar%"
    intercept_redirects: "%debug_redirects%"

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    use_controller: "%use_assetic_controller%"

swiftmailer:
    delivery_address: ['faainttt@gmail.com']

services:
    mbh.channelmanager.myallocator:
        class: Tests\Bundle\ChannelManagerBundle\Services\ChannelManagerServiceMock

    mbh.channelmanager.booking:
        class: Tests\Bundle\ChannelManagerBundle\Services\ChannelManagerServiceMock

    mbh.channelmanager.ostrovok:
        class: Tests\Bundle\ChannelManagerBundle\Services\ChannelManagerServiceMock

    mbh.channelmanager.hundred_one_hotels:
        class: Tests\Bundle\ChannelManagerBundle\Services\ChannelManagerServiceMock

    mbh.channelmanager.expedia:
        class: Tests\Bundle\ChannelManagerBundle\Services\ChannelManagerServiceMock

    mbh.channelmanager.vashotel:
        class: Tests\Bundle\ChannelManagerBundle\Services\ChannelManagerServiceMock