imports:
    - { resource: config.yml }
    - { resource: config_dev_data.yml }
    - { resource: security_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.php_bridge
    profiler:
        enabled: true

swiftmailer:
    disable_delivery: true

parameters:
    mb_user_pwd: 'mb_user_pwd'
    mbh.environment: "prod" #это для обхода проверки \MBH\Bundle\BaseBundle\EventListener\OnController::onKernelController
    mbh_cache:
        is_enabled: true
        prefix: mbh
        lifetime: 7
        logs: false
        search:
            months: 6
            max_duration: 21
            min_duration: 3
security:
    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: false

    firewalls:
        main:
            context: test_content
            http_basic: ~
            form_login: false
            remember_me: false
            stateless: false


liip_functional_test:
  authentication:
    username: "admin"
    password: "admin"
