imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.php_bridge
    profiler:
        enabled: true

swiftmailer:
    disable_delivery: true

parameters:
    mongodb_url: 'mongodb://mbh-mongo:27017/sandbox_template_db'
    mongodb_database: sandbox_template_db

security:
    firewalls:
        main:
            http_basic: ~
            form_login: false
            remember_me: false

doctrine_mongodb:
    connections:
        default:
            server: "mongodb://%mongodb_host%/%mongodb_database%%mongodb_options%"