imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.php_bridge
    profiler:
        enabled: true
    csrf_protection:
        enabled: true

swiftmailer:
    disable_delivery: true

parameters:
    mbh.environment: "prod" #это для обхода проверки \MBH\Bundle\BaseBundle\EventListener\OnController::onKernelController
    mbh_cache:
        is_enabled: true
        prefix: mbh
        lifetime: 7
        logs: false
        search:
            months: 6
            max_duration: 21
            min_duration: 3
security:
    firewalls:
        main:
            http_basic: ~
            form_login: true
            remember_me: false

liip_functional_test:
  authentication:
    username: "admin"
    password: "admin"