framework:
    workflows:
        installation:
            type: 'workflow'
            marking_store:
                type: 'single_state'
                arguments:
                    - 'currentPlace'
            supports:
                - MBH\Bundle\BillingBundle\Document\InstallationWorkflow
            places:
              - new
              - progress
              - installed
              - error
            transitions:
                install:
                    from: new
                    to: progress
                installed:
                    from: progress
                    to: installed
                error:
                    from: progress
                    to: error
                rollback:
                    from: error
                    to: new

        after_installation:
            type: 'workflow'
            marking_store:
                type: 'single_state'
                arguments:
                    - 'currentPlace'
            supports:
                - MBH\Bundle\BillingBundle\Document\AfterInstallationWorkFlow
            places:
              - new
              - progress
              - installed
              - error
            transitions:
                after_install:
                    from: new
                    to: progress
                installed:
                    from: progress
                    to: installed
                error:
                    from: progress
                    to: error
