<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class GedmoLoggableDocumentLogEntryHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['action'])) {
            $value = $data['action'];
            $return = (string) $value;
            $this->class->reflFields['action']->setValue($document, $return);
            $hydratedData['action'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['loggedAt'])) {
            $value = $data['loggedAt'];
            if ($value === null) { $return = null; } else { $return = \Doctrine\ODM\MongoDB\Types\DateType::getDateTime($value); }
            $this->class->reflFields['loggedAt']->setValue($document, clone $return);
            $hydratedData['loggedAt'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['objectId'])) {
            $value = $data['objectId'];
            $return = (string) $value;
            $this->class->reflFields['objectId']->setValue($document, $return);
            $hydratedData['objectId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['objectClass'])) {
            $value = $data['objectClass'];
            $return = (string) $value;
            $this->class->reflFields['objectClass']->setValue($document, $return);
            $hydratedData['objectClass'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['version'])) {
            $value = $data['version'];
            $return = (int) $value;
            $this->class->reflFields['version']->setValue($document, $return);
            $hydratedData['version'] = $return;
        }

        /** @Field(type="hash") */
        if (isset($data['data'])) {
            $value = $data['data'];
            $return = $value;
            $this->class->reflFields['data']->setValue($document, $return);
            $hydratedData['data'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['username'])) {
            $value = $data['username'];
            $return = (string) $value;
            $this->class->reflFields['username']->setValue($document, $return);
            $hydratedData['username'] = $return;
        }
        return $hydratedData;
    }
}