<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class GedmoTranslatableDocumentTranslationHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['locale'])) {
            $value = $data['locale'];
            $return = (string) $value;
            $this->class->reflFields['locale']->setValue($document, $return);
            $hydratedData['locale'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['objectClass'])) {
            $value = $data['objectClass'];
            $return = (string) $value;
            $this->class->reflFields['objectClass']->setValue($document, $return);
            $hydratedData['objectClass'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['field'])) {
            $value = $data['field'];
            $return = (string) $value;
            $this->class->reflFields['field']->setValue($document, $return);
            $hydratedData['field'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['foreignKey'])) {
            $value = $data['foreignKey'];
            $return = (string) $value;
            $this->class->reflFields['foreignKey']->setValue($document, $return);
            $hydratedData['foreignKey'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['content'])) {
            $value = $data['content'];
            $return = (string) $value;
            $this->class->reflFields['content']->setValue($document, $return);
            $hydratedData['content'] = $return;
        }
        return $hydratedData;
    }
}