<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class MBHBundlePackageBundleDocumentCreditCardHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="string") */
        if (isset($data['type'])) {
            $value = $data['type'];
            $return = (string) $value;
            $this->class->reflFields['type']->setValue($document, $return);
            $hydratedData['type'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['number'])) {
            $value = $data['number'];
            $return = (string) $value;
            $this->class->reflFields['number']->setValue($document, $return);
            $hydratedData['number'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['cardholder'])) {
            $value = $data['cardholder'];
            $return = (string) $value;
            $this->class->reflFields['cardholder']->setValue($document, $return);
            $hydratedData['cardholder'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['date'])) {
            $value = $data['date'];
            $return = (string) $value;
            $this->class->reflFields['date']->setValue($document, $return);
            $hydratedData['date'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['cvc'])) {
            $value = $data['cvc'];
            $return = (string) $value;
            $this->class->reflFields['cvc']->setValue($document, $return);
            $hydratedData['cvc'] = $return;
        }
        return $hydratedData;
    }
}