<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class MBHBundleOnlineBundleDocumentInvitedTouristHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="string") */
        if (isset($data['firstName'])) {
            $value = $data['firstName'];
            $return = (string) $value;
            $this->class->reflFields['firstName']->setValue($document, $return);
            $hydratedData['firstName'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['lastName'])) {
            $value = $data['lastName'];
            $return = (string) $value;
            $this->class->reflFields['lastName']->setValue($document, $return);
            $hydratedData['lastName'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['sex'])) {
            $value = $data['sex'];
            $return = (string) $value;
            $this->class->reflFields['sex']->setValue($document, $return);
            $hydratedData['sex'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['birthday'])) {
            $value = $data['birthday'];
            $return = (string) $value;
            $this->class->reflFields['birthday']->setValue($document, $return);
            $hydratedData['birthday'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['birthplace'])) {
            $value = $data['birthplace'];
            $return = (string) $value;
            $this->class->reflFields['birthplace']->setValue($document, $return);
            $hydratedData['birthplace'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['citizenship'])) {
            $value = $data['citizenship'];
            $return = (string) $value;
            $this->class->reflFields['citizenship']->setValue($document, $return);
            $hydratedData['citizenship'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['passport'])) {
            $value = $data['passport'];
            $return = (string) $value;
            $this->class->reflFields['passport']->setValue($document, $return);
            $hydratedData['passport'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['expiry'])) {
            $value = $data['expiry'];
            $return = (string) $value;
            $this->class->reflFields['expiry']->setValue($document, $return);
            $hydratedData['expiry'] = $return;
        }
        return $hydratedData;
    }
}