<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class MBHBundleClientBundleDocumentPayanywayHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="string") */
        if (isset($data['payanywayMntId'])) {
            $value = $data['payanywayMntId'];
            $return = (string) $value;
            $this->class->reflFields['payanywayMntId']->setValue($document, $return);
            $hydratedData['payanywayMntId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['payanywayKey'])) {
            $value = $data['payanywayKey'];
            $return = (string) $value;
            $this->class->reflFields['payanywayKey']->setValue($document, $return);
            $hydratedData['payanywayKey'] = $return;
        }
        return $hydratedData;
    }
}