<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class MBHBundleChannelManagerBundleDocumentServiceHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @ReferenceOne */
        if (isset($data['service'])) {
            $reference = $data['service'];
            if (isset($this->class->fieldMappings['service']['simple']) && $this->class->fieldMappings['service']['simple']) {
                $className = $this->class->fieldMappings['service']['targetDocument'];
                $mongoId = $reference;
            } else {
                $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['service'], $reference);
                $mongoId = $reference['$id'];
            }
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['service']->setValue($document, $return);
            $hydratedData['service'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['serviceId'])) {
            $value = $data['serviceId'];
            $return = (string) $value;
            $this->class->reflFields['serviceId']->setValue($document, $return);
            $hydratedData['serviceId'] = $return;
        }
        return $hydratedData;
    }
}