<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class MBHBundleChannelManagerBundleDocumentTariffHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="string") */
        if (isset($data['tariffId'])) {
            $value = $data['tariffId'];
            $return = (string) $value;
            $this->class->reflFields['tariffId']->setValue($document, $return);
            $hydratedData['tariffId'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['tariff'])) {
            $reference = $data['tariff'];
            if (isset($this->class->fieldMappings['tariff']['simple']) && $this->class->fieldMappings['tariff']['simple']) {
                $className = $this->class->fieldMappings['tariff']['targetDocument'];
                $mongoId = $reference;
            } else {
                $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['tariff'], $reference);
                $mongoId = $reference['$id'];
            }
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['tariff']->setValue($document, $return);
            $hydratedData['tariff'] = $return;
        }
        return $hydratedData;
    }
}