<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class MBHBundlePriceBundleDocumentTariffChildOptionsHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="boolean") */
        if (isset($data['inheritPrices'])) {
            $value = $data['inheritPrices'];
            $return = (bool) $value;
            $this->class->reflFields['inheritPrices']->setValue($document, $return);
            $hydratedData['inheritPrices'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['inheritRestrictions'])) {
            $value = $data['inheritRestrictions'];
            $return = (bool) $value;
            $this->class->reflFields['inheritRestrictions']->setValue($document, $return);
            $hydratedData['inheritRestrictions'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['inheritRooms'])) {
            $value = $data['inheritRooms'];
            $return = (bool) $value;
            $this->class->reflFields['inheritRooms']->setValue($document, $return);
            $hydratedData['inheritRooms'] = $return;
        }
        return $hydratedData;
    }
}