<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class MBHBundleClientBundleDocumentRobokassaHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="string") */
        if (isset($data['robokassaMerchantLogin'])) {
            $value = $data['robokassaMerchantLogin'];
            $return = (string) $value;
            $this->class->reflFields['robokassaMerchantLogin']->setValue($document, $return);
            $hydratedData['robokassaMerchantLogin'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['robokassaMerchantPass1'])) {
            $value = $data['robokassaMerchantPass1'];
            $return = (string) $value;
            $this->class->reflFields['robokassaMerchantPass1']->setValue($document, $return);
            $hydratedData['robokassaMerchantPass1'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['robokassaMerchantPass2'])) {
            $value = $data['robokassaMerchantPass2'];
            $return = (string) $value;
            $this->class->reflFields['robokassaMerchantPass2']->setValue($document, $return);
            $hydratedData['robokassaMerchantPass2'] = $return;
        }
        return $hydratedData;
    }
}