###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.5"
services:

    az-memcached:
      image: memcached:alpine
      container_name: az-memcached
      hostname: az-memcache
      networks:
        - mynetwork
      restart: always


    az-redis:
      image: redis:alpine
      container_name: az-redis
      hostname: az-redis
      networks:
        - mynetwork
      restart: always

    az-rabbitmq:
      image: rabbitmq:latest
      container_name: az-rabbitmq
      hostname: az-rabbit
      environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "rabbitmq"
        RABBITMQ_DEFAULT_VHOST: "/"
      ports:
        - "15674:15672"
        - "5674:5672"
      volumes:
        - ./phpdocker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      networks:
        - mynetwork
      restart: always

    az-mongo:
      image: mongo:3.6
      container_name: az-mongo
      hostname: az-mongo
      command: mongod --setParameter failIndexKeyTooLong=false
      volumes:
        - az_mongo_data:/data/db
      ports:
        - "27019:27017"
      networks:
        - mynetwork
      restart: always

    az-php-fpm:
      build: phpdocker/php-fpm
      container_name: az-php-fpm
      hostname: az-php-fpm
      working_dir: /var/www/mbh
      volumes:
        - ..:/var/www/mbh
        - ./phpdocker/php-fpm/php-ini-overrides-fpm.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
        - ./phpdocker/php-fpm/php-ini-overrides-cli.ini:/etc/php/7.3/cli/conf.d/99-overrides.ini
        - ./phpdocker/php-fpm/supervisor.conf.d:/etc/supervisor/conf.d
        - ./phpdocker/php-fpm/fish:/root/.config/fish/functions
        - /tmp/:/tmp/
      ports:
        - "9003:9000"
      networks:
        - mynetwork
      restart: always

volumes:
  az_mongo_data:
    driver: local

networks:
  mynetwork:
    name: az-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
