---
- name: Setup virtual machine
  hosts: all
  remote_user: ubuntu
  become: True
  roles:
    - nginx
    - user_manager
    - common
    - nodejs
    - php
    - composer
    - mongodb
    - npm_install
    - rabbitmq
    - redis
    - memcached
  vars_files:
    - default_vars.yml
