services:
    mbh.api_serializer:
        class: MBH\Bundle\ApiBundle\Service\ApiSerializer
        arguments: ['@mbh.serializer']

    mbh.api_request_manager:
        class: MBH\Bundle\ApiBundle\Service\ApiRequestManager
        arguments: ['@mbh.api_serializer', '@mbh.serializer']
