parameters:
    log_file.mb_site: !php/const:MBH\Bundle\OnlineBundle\Command\MBSiteCreateSiteContentMigrationCommand::FILE_LOG_NAME

services:
    mbh.online.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, ['@mbh.online.logger_handler']]

    mbh.online.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: ["%kernel.logs_dir%/%kernel.environment%.online.log", 200]

    mbh.api_response_compiler:
        class: MBH\Bundle\OnlineBundle\Services\ApiResponseCompiler
        arguments:
            - '@translator'

    mbh.api_handler:
        class: MBH\Bundle\OnlineBundle\Services\ApiHandler
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - '@MBH\Bundle\OnlineBundle\Document\SettingsOnlineForm\FormConfigManager'

    mbh.form_type:
        class: MBH\Bundle\OnlineBundle\Form\SettingsOnlineForm\FormType
        arguments: ['@mbh.client_manager', '%mbh.online.form%']
        tags:
            {name: form.type}

    MBH\Bundle\OnlineBundle\Services\PaymentForm\SearchFormResult:
        arguments:
            - '@translator'

    mbh.online.search_order:
        class: MBH\Bundle\OnlineBundle\Services\PaymentForm\SearchForm
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - '@MBH\Bundle\OnlineBundle\Services\PaymentForm\PaymentFormManager'
            - '@MBH\Bundle\OnlineBundle\Services\PaymentForm\SearchFormResult'

    mbh.payment_types_type:
        class: MBH\Bundle\OnlineBundle\Form\PaymentTypesType
        arguments: ['%mbh.online.form%']
        tags:
            {name: form.type}

    mbh.site_form:
        class: MBH\Bundle\OnlineBundle\Form\SiteForm
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - '@translator'
            - '@mbh.site_manager'
            - '%kernel.environment%'
        tags:
            {name: form.type}

    mbh.site_manager:
        class: MBH\Bundle\OnlineBundle\Services\SiteManager
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - '@mbh.document_fields_manager'
            - '@translator'
            - '@mbh.warnings_compiler'
            - '@mbh.billing.api'
            - '@mbh.client_manager'
            - '@MBH\Bundle\OnlineBundle\Document\SettingsOnlineForm\FormConfigManager'
            - '@MBH\Bundle\OnlineBundle\Services\PaymentForm\PaymentFormManager'

    MBH\Bundle\OnlineBundle\Services\RenderPaymentButton:
        arguments:
            - '@twig'
            - '@mbh.client_config_manager'
            - '@translator'
            - '@MBH\Bundle\ClientBundle\Service\PaymentSystem\Wrapper\PaymentSystemWrapperFactory'

    mbh.online_payment_form.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
        - [pushHandler, ['@mbh.online_payment_form.logger_handler']]

    mbh.online_payment_form.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: ["%kernel.logs_dir%/%kernel.environment%.online.log", 200]

    MBH\Bundle\OnlineBundle\EventListener\PaymentFormSubscriber:
        arguments:
            - '@service_container'
        tags:
            - {name: doctrine_mongodb.odm.event_subscriber, connection: default}

    MBH\Bundle\OnlineBundle\Services\AvailableSocialNetworkingServices:
        arguments:
            - '%locale%'

    MBH\Bundle\OnlineBundle\Form\SettingsOnlineForm\FieldsNameType:
        arguments: ['@mbh.client_config_manager']
        tags:
            - {name: form.type}

    MBH\Bundle\OnlineBundle\Services\DataForSearchForm:
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - '@mbh.helper'
            - '@router'
            - '@request_stack'

    mbh.mb_site.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, ['@mbh.mb_site.logger_handler']]

    mbh.mb_site.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments:
            - "%kernel.logs_dir%/%kernel.environment%.%log_file.mb_site%"
            - 200

    MBH\Bundle\OnlineBundle\Services\MBSite\StyleDataFromFile:
      arguments:
        - '@mbh.sentry_logger'
        - '%kernel.root_dir%'

    MBH\Bundle\OnlineBundle\Services\SearchForm\MBSiteSearchFormStyle:
        arguments:
            - '@MBH\Bundle\OnlineBundle\Services\MBSite\StyleDataFromFile'

    MBH\Bundle\OnlineBundle\Services\ResultsForm\MBSiteResultFormStyle:
        arguments:
            - '@MBH\Bundle\OnlineBundle\Services\MBSite\StyleDataFromFile'

    mbh.online_payment_form.validator:
        class: MBH\Bundle\OnlineBundle\Services\OnlineFormValidator

    MBH\Bundle\OnlineBundle\Services\SearchForm\MBSiteFormConfigDataService:
        arguments:
            - '@MBH\Bundle\OnlineBundle\Services\SearchForm\MBSiteSearchFormStyle'
            - '@MBH\Bundle\OnlineBundle\Services\ResultsForm\MBSiteResultFormStyle'
            - '@doctrine.odm.mongodb.document_manager'
            - '%locale%'

    MBH\Bundle\OnlineBundle\Document\SettingsOnlineForm\FormConfigManager:
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - '@MBH\Bundle\OnlineBundle\Services\SearchForm\MBSiteFormConfigDataService'
            - '@mbh.client_config_manager'

    MBH\Bundle\OnlineBundle\Services\ParamConverter\FormConfigConverter:
        arguments:
            - '@MBH\Bundle\OnlineBundle\Document\SettingsOnlineForm\FormConfigManager'
        tags:
            - {name: request.param_converter, converter: form_config_converter}

    MBH\Bundle\OnlineBundle\Services\ParamConverter\PaymentFormConfigConverter:
        arguments:
            - '@MBH\Bundle\OnlineBundle\Services\PaymentForm\PaymentFormManager'
        tags:
            - {name: request.param_converter, converter: payment_form_config_converter}

    MBH\Bundle\OnlineBundle\Services\MBSite\v2\:
        resource: '%kernel.root_dir%/../src/MBH/Bundle/OnlineBundle/Services/MBSite/v2/*'
        arguments:
            - '@vich_uploader.templating.helper.uploader_helper'
            - '@liip_imagine.cache.manager'

    MBH\Bundle\OnlineBundle\EventListener\CheckSiteMangerListener:
        arguments:
            - '@mbh.client_config_manager'
            - '@mbh.site_manager'
            - '@mbh.api_response_compiler'
        tags:
            - {name: kernel.event_listener, event: kernel.controller, method: checkSiteManger, priority: 11}

    MBH\Bundle\OnlineBundle\EventListener\AutoSiteResolveParamListener:
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - '@mbh.api_response_compiler'
            - '@mbh.site_manager'
            - '@MBH\Bundle\OnlineBundle\Document\SettingsOnlineForm\FormConfigManager'
        tags:
            - {name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 10 }

    MBH\Bundle\OnlineBundle\EventListener\ApiResponseCompilerViewListener:
        tags:
            - {name: kernel.event_listener, event: kernel.view}

    MBH\Bundle\OnlineBundle\EventListener\SiteConfigSubscriber:
        tags:
            - {name: doctrine_mongodb.odm.event_subscriber, connection: default }

    MBH\Bundle\OnlineBundle\Services\PaymentForm\MBSitePaymentFormConfigData:
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - '@MBH\Bundle\OnlineBundle\Services\MBSite\StyleDataFromFile'

    MBH\Bundle\OnlineBundle\Services\PaymentForm\PaymentFormManager:
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - '@MBH\Bundle\OnlineBundle\Services\PaymentForm\MBSitePaymentFormConfigData'
            - '@mbh.client_config_manager'

    MBH\Bundle\OnlineBundle\Services\PaymentForm\ContactHotelPaymentForm:
        arguments:
            - '@translator'

    MBH\Bundle\OnlineBundle\Services\PaymentForm\PaymentSystemHelper:
        arguments:
            - '@translator'
            - '@mbh.client_config_manager'
            - '@mbh.payment_extra_data'
            - '@MBH\Bundle\OnlineBundle\Services\PaymentForm\ContactHotelPaymentForm'
