services:
    mbh.online.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, ['@mbh.online.logger_handler']]

    mbh.online.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: ["%kernel.logs_dir%/%kernel.environment%.online.log", 200]

    mbh.api_response_compiler:
        class: MBH\Bundle\OnlineBundle\Services\ApiResponseCompiler
        arguments:
            - '@translator'

    mbh.api_handler:
        class: MBH\Bundle\OnlineBundle\Services\ApiHandler
        arguments:
            - '@doctrine.odm.mongodb.document_manager'

    mbh.form_type:
        class: MBH\Bundle\OnlineBundle\Form\FormType
        arguments: ['@mbh.client_manager', '%mbh.online.form%']
        tags:
            {name: form.type}

    mbh.online.search_order:
        class: MBH\Bundle\OnlineBundle\Lib\SearchForm
        arguments: ['@service_container']

    mbh.payment_types_type:
        class: MBH\Bundle\OnlineBundle\Form\PaymentTypesType
        arguments: ['%mbh.online.form%']
        tags:
            {name: form.type}

    mbh.site_form:
        class: MBH\Bundle\OnlineBundle\Form\SiteForm
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - '@translator'
            - '@mbh.site_manager'
            - '%kernel.environment%'
        tags:
            {name: form.type}

    mbh.site_manager:
        class: MBH\Bundle\OnlineBundle\Services\SiteManager
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - '@mbh.document_fields_manager'
            - '@translator'
            - '@mbh.warnings_compiler'
            - '@mbh.billing.api'
            - '@mbh.client_manager'

    MBH\Bundle\OnlineBundle\Services\RenderPaymentButton:
        arguments:
            - '@twig'
            - '@mbh.client_config_manager'
            - '@translator'
            - '@MBH\Bundle\ClientBundle\Service\PaymentSystem\Wrapper\PaymentSystemWrapperFactory'