services:
    mbh.online.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, ['@mbh.online.logger_handler']]

    mbh.online.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: ["%kernel.logs_dir%/%kernel.environment%.online.log", 200]

    mbh.form_type:
        class: MBH\Bundle\OnlineBundle\Form\FormType
        arguments: ['%country_type%']
        tags:
            {name: form.type}