services:
    mbh.online.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, ['@mbh.online.logger_handler']]

    mbh.online.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: ["%kernel.logs_dir%/%kernel.environment%.online.log", 200]

    mbh.online.search_order:
        class: MBH\Bundle\OnlineBundle\Lib\SearchForm
        arguments: ['@service_container']

    mbh.online.search_order.logger:
            class:     Symfony\Bridge\Monolog\Logger
            arguments: [app]
            calls:
                - [pushHandler, ['@mbh.online.search_order.logger_handler']]

    mbh.online.search_order.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: ["%kernel.logs_dir%/%kernel.environment%.search_order.log", 200]