###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '2'

services:
  mbh-memcached2:
    image: memcached:1.4
    container_name: mbh-memcached2
    ports:
      - "11211:11211"

  mbh-rabbitmq2:
    image: rabbitmq:latest
    container_name: mbh-rabbitmq2
    hostname: "mbh-rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15673:15672"
      - "5673:5672"
    labels:
      NAME: "mbh-rabbitmq"
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"

  mbh-redis2:
    image: redis:latest
    container_name: mbh-redis2
    ports:
      - "6378:6379"

  mbh-mongo2:
    image: mongo:3.4
    container_name: mbh-mongo2
    command: mongod --setParameter failIndexKeyTooLong=false
    volumes:
      - ./mongodb/mongodb.conf:/etc/mongodb.conf
      - ./mongo_data2:/data/db
    ports:
      - "27018:27017"

  mbh-php-fpm2:
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
    container_name: mbh-php-fpm2
    volumes:
      - ..:/var/www/mbh
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/cli/conf.d/99-overrides.ini
      - ./php-fpm/start.sh:/start.sh
      - ./php-fpm/fish:/root/.config/fish/functions
      - /tmp/:/tmp/
      - ./php-fpm/keys:/root/.ssh
    links:
      - mbh-memcached2
      - mbh-mongo2
      - mbh-rabbitmq2
      - mbh-redis2

  mbh-php-cli2:
    build:
      context: .
      dockerfile: php-cli/Dockerfile
    container_name: mbh-php-cli2
    volumes:
      - ..:/var/www/mbh
      - ./php-cli/php-ini-overrides.ini:/etc/php/7.1/cli/conf.d/99-overrides.ini
      - ./php-cli/fish:/root/.config/fish/functions
      - /tmp/:/tmp/
    links:
      - mbh-memcached2
      - mbh-mongo2
      - mbh-rabbitmq2
      - mbh-redis2

  mbh-webserver2:
    image: phpdockerio/nginx:latest
    container_name: mbh-webserver2
    volumes:
      - ..:/var/www/mbh
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/fastcgi_param_client:/etc/nginx/fastcgi_param_client
      - ./nginx/cert/:/etc/cert/
    ports:
      - "9090:80"
      - "9443:443"
    links:
      - mbh-php-fpm2
