---
- name: Add group
  group:
    name: vagrant

- name: Create user ang group vagrant
  user:
    name: vagrant
    password: vagrant
    groups: vagrant

- name: User www-data add group maxibooking
  user:
    name: www-data
    groups: vagrant
