<?php

namespace MongoDBODMProxies\__CG__\MBH\Bundle\ClientBundle\Document;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Uniteller extends \MBH\Bundle\ClientBundle\Document\Uniteller implements \Doctrine\ODM\MongoDB\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'unitellerShopIDP', 'unitellerPassword'];
        }

        return ['__isInitialized__', 'unitellerShopIDP', 'unitellerPassword'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Uniteller $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setUnitellerShopIDP($unitellerShopIDP)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnitellerShopIDP', [$unitellerShopIDP]);

        return parent::setUnitellerShopIDP($unitellerShopIDP);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnitellerShopIDP()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnitellerShopIDP', []);

        return parent::getUnitellerShopIDP();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnitellerPassword($unitellerPassword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnitellerPassword', [$unitellerPassword]);

        return parent::setUnitellerPassword($unitellerPassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnitellerPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnitellerPassword', []);

        return parent::getUnitellerPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getCheckPaymentData(\MBH\Bundle\CashBundle\Document\CashDocument $cashDocument)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheckPaymentData', [$cashDocument]);

        return parent::getCheckPaymentData($cashDocument);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormData(\MBH\Bundle\CashBundle\Document\CashDocument $cashDocument, $url = NULL, $checkUrl = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormData', [$cashDocument, $url, $checkUrl]);

        return parent::getFormData($cashDocument, $url, $checkUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getSignature(\MBH\Bundle\CashBundle\Document\CashDocument $cashDocument, $url = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignature', [$cashDocument, $url]);

        return parent::getSignature($cashDocument, $url);
    }

    /**
     * {@inheritDoc}
     */
    public function checkRequest(\Symfony\Component\HttpFoundation\Request $request)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkRequest', [$request]);

        return parent::checkRequest($request);
    }

}
