<?php

namespace MongoDBODMProxies\__CG__\MBH\Bundle\PackageBundle\Document;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tourist extends \MBH\Bundle\PackageBundle\Document\Tourist implements \Doctrine\ODM\MongoDB\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = ['orders' => NULL, 'packages' => NULL];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {
        unset($this->orders, $this->packages);

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * 
     * @param string $name
     */
    public function __get($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);

            return $this->$name;
        }

        trigger_error(sprintf('Undefined property: %s::$%s', __CLASS__, $name), E_USER_NOTICE);
    }

    /**
     * 
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);

            $this->$name = $value;

            return;
        }

        $this->$name = $value;
    }

    /**
     * 
     * @param  string $name
     * @return boolean
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->__getLazyProperties())) {
            $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', [$name]);

            return isset($this->$name);
        }

        return false;
    }

    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'orders', 'packages', 'cashDocuments', 'firstName', 'lastName', 'patronymic', 'fullName', 'birthday', 'sex', 'phone', 'mobilePhone', 'messenger', 'email', 'note', 'citizenship', 'birthplace', 'addressObjectDecomposed', 'addressObjectCombined', 'documentRelation', 'migration', 'visa', 'communicationLanguage', 'isUnwelcome', 'id', 'isEnabled', 'createdAt', 'updatedAt', 'deletedAt', 'createdBy', 'updatedBy', 'inn'];
        }

        return ['__isInitialized__', 'cashDocuments', 'firstName', 'lastName', 'patronymic', 'fullName', 'birthday', 'sex', 'phone', 'mobilePhone', 'messenger', 'email', 'note', 'citizenship', 'birthplace', 'addressObjectDecomposed', 'addressObjectCombined', 'documentRelation', 'migration', 'visa', 'communicationLanguage', 'isUnwelcome', 'id', 'isEnabled', 'createdAt', 'updatedAt', 'deletedAt', 'createdBy', 'updatedBy', 'inn'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tourist $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

            unset($this->orders, $this->packages);
        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getShortName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShortName', []);

        return parent::getShortName();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastNameWithInitials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastNameWithInitials', []);

        return parent::getLastNameWithInitials();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', []);

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', [$lastName]);

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', []);

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', [$firstName]);

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getPatronymic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatronymic', []);

        return parent::getPatronymic();
    }

    /**
     * {@inheritDoc}
     */
    public function setPatronymic($patronymic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatronymic', [$patronymic]);

        return parent::setPatronymic($patronymic);
    }

    /**
     * {@inheritDoc}
     */
    public function getSex()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSex', []);

        return parent::getSex();
    }

    /**
     * {@inheritDoc}
     */
    public function setSex($sex)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSex', [$sex]);

        return parent::setSex($sex);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressObjectCombined()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressObjectCombined', []);

        return parent::getAddressObjectCombined();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressObjectCombined($addressObjectCombined)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressObjectCombined', [$addressObjectCombined]);

        return parent::setAddressObjectCombined($addressObjectCombined);
    }

    /**
     * {@inheritDoc}
     */
    public function setDocument($document)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocument', [$document]);

        return parent::setDocument($document);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocument()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocument', []);

        return parent::getDocument();
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone($original = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', [$original]);

        return parent::getPhone($original);
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getMobilePhone($original = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMobilePhone', [$original]);

        return parent::getMobilePhone($original);
    }

    /**
     * {@inheritDoc}
     */
    public function setMobilePhone($mobilePhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMobilePhone', [$mobilePhone]);

        return parent::setMobilePhone($mobilePhone);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessenger()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessenger', []);

        return parent::getMessenger();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessenger($messenger)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessenger', [$messenger]);

        return parent::setMessenger($messenger);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote($note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', [$note]);

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', []);

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function guessGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'guessGender', []);

        return parent::guessGender();
    }

    /**
     * {@inheritDoc}
     */
    public function generateFullName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generateFullName', []);

        return parent::generateFullName();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpdate', []);

        return parent::preUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function generateFullNameWithAge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generateFullNameWithAge', []);

        return parent::generateFullNameWithAge();
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthday', []);

        return parent::getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthday($birthday)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthday', [$birthday]);

        return parent::setBirthday($birthday);
    }

    /**
     * {@inheritDoc}
     */
    public function getAge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAge', []);

        return parent::getAge();
    }

    /**
     * {@inheritDoc}
     */
    public function addPackage(\MBH\Bundle\PackageBundle\Document\Package $package)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPackage', [$package]);

        return parent::addPackage($package);
    }

    /**
     * {@inheritDoc}
     */
    public function removePackage(\MBH\Bundle\PackageBundle\Document\Package $package)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePackage', [$package]);

        return parent::removePackage($package);
    }

    /**
     * {@inheritDoc}
     */
    public function getPackages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackages', []);

        return parent::getPackages();
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getFullName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullName', []);

        return parent::getFullName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFullName($fullName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFullName', [$fullName]);

        return parent::setFullName($fullName);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addCashDocument(\MBH\Bundle\CashBundle\Document\CashDocument $cashDocument)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCashDocument', [$cashDocument]);

        return parent::addCashDocument($cashDocument);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCashDocument(\MBH\Bundle\CashBundle\Document\CashDocument $cashDocument)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCashDocument', [$cashDocument]);

        return parent::removeCashDocument($cashDocument);
    }

    /**
     * {@inheritDoc}
     */
    public function getCashDocuments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCashDocuments', []);

        return parent::getCashDocuments();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrder(\MBH\Bundle\PackageBundle\Document\Order $order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrder', [$order]);

        return parent::addOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrder(\MBH\Bundle\PackageBundle\Document\Order $order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrder', [$order]);

        return parent::removeOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrders', []);

        return parent::getOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function getCitizenship()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCitizenship', []);

        return parent::getCitizenship();
    }

    /**
     * {@inheritDoc}
     */
    public function setCitizenship(\MBH\Bundle\VegaBundle\Document\VegaState $citizenship = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCitizenship', [$citizenship]);

        return parent::setCitizenship($citizenship);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthplace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthplace', []);

        return parent::getBirthplace();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthplace(\MBH\Bundle\PackageBundle\Document\BirthPlace $birthplace = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthplace', [$birthplace]);

        return parent::setBirthplace($birthplace);
    }

    /**
     * {@inheritDoc}
     */
    public function preSave()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preSave', []);

        return parent::preSave();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressObjectDecomposed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressObjectDecomposed', []);

        return parent::getAddressObjectDecomposed();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressObjectDecomposed(\MBH\Bundle\PackageBundle\Document\AddressObjectDecomposed $addressObjectDecomposed = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressObjectDecomposed', [$addressObjectDecomposed]);

        return parent::setAddressObjectDecomposed($addressObjectDecomposed);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentRelation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentRelation', []);

        return parent::getDocumentRelation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumentRelation(\MBH\Bundle\PackageBundle\Document\DocumentRelation $documentRelation = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumentRelation', [$documentRelation]);

        return parent::setDocumentRelation($documentRelation);
    }

    /**
     * {@inheritDoc}
     */
    public function getMigration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMigration', []);

        return parent::getMigration();
    }

    /**
     * {@inheritDoc}
     */
    public function setMigration(\MBH\Bundle\PackageBundle\Document\Migration $migration = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMigration', [$migration]);

        return parent::setMigration($migration);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisa', []);

        return parent::getVisa();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisa(\MBH\Bundle\PackageBundle\Document\Visa $visa = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisa', [$visa]);

        return parent::setVisa($visa);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommunicationLanguage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommunicationLanguage', []);

        return parent::getCommunicationLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommunicationLanguage($communicationLanguage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommunicationLanguage', [$communicationLanguage]);

        return parent::setCommunicationLanguage($communicationLanguage);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsUnwelcome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsUnwelcome', []);

        return parent::getIsUnwelcome();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsUnwelcome($isUnwelcome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsUnwelcome', [$isUnwelcome]);

        return parent::setIsUnwelcome($isUnwelcome);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsEnabled', []);

        return parent::getIsEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsEnabled($isEnabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsEnabled', [$isEnabled]);

        return parent::setIsEnabled($isEnabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt(\DateTime $deletedAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', [$deletedAt]);

        return parent::setDeletedAt($deletedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', []);

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function isDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDeleted', []);

        return parent::isDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$createdBy]);

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy($updatedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', [$updatedBy]);

        return parent::setUpdatedBy($updatedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', []);

        return parent::getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function getInn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInn', []);

        return parent::getInn();
    }

    /**
     * {@inheritDoc}
     */
    public function setInn($inn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInn', [$inn]);

        return parent::setInn($inn);
    }

}
