<?php

namespace MongoDBODMProxies\__CG__\MBH\Bundle\PackageBundle\Document;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Package extends \MBH\Bundle\PackageBundle\Document\Package implements \Doctrine\ODM\MongoDB\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'order', 'services', 'tariff', 'roomType', 'accommodation', 'tourists', 'number', 'numberWithPrefix', 'adults', 'children', 'begin', 'end', 'promotion', 'promotionTotal', 'price', 'originalPrice', 'totalOverwrite', 'pricesByDate', 'prices', 'servicesPrice', 'note', 'purposeOfArrival', 'channelManagerType', 'channelManagerId', 'arrivalTime', 'departureTime', 'discount', 'isPercentDiscount', 'isCheckIn', 'isCheckOut', 'isSmoking', 'corrupted', 'isLocked', 'isForceBooking', 'id', 'isEnabled', 'createdAt', 'updatedAt', 'deletedAt', 'createdBy', 'updatedBy'];
        }

        return ['__isInitialized__', 'order', 'services', 'tariff', 'roomType', 'accommodation', 'tourists', 'number', 'numberWithPrefix', 'adults', 'children', 'begin', 'end', 'promotion', 'promotionTotal', 'price', 'originalPrice', 'totalOverwrite', 'pricesByDate', 'prices', 'servicesPrice', 'note', 'purposeOfArrival', 'channelManagerType', 'channelManagerId', 'arrivalTime', 'departureTime', 'discount', 'isPercentDiscount', 'isCheckIn', 'isCheckOut', 'isSmoking', 'corrupted', 'isLocked', 'isForceBooking', 'id', 'isEnabled', 'createdAt', 'updatedAt', 'deletedAt', 'createdBy', 'updatedBy'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Package $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setTariff(\MBH\Bundle\PriceBundle\Document\Tariff $tariff)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTariff', [$tariff]);

        return parent::setTariff($tariff);
    }

    /**
     * {@inheritDoc}
     */
    public function getTariff()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTariff', []);

        return parent::getTariff();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoomType(\MBH\Bundle\HotelBundle\Document\RoomType $roomType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoomType', [$roomType]);

        return parent::setRoomType($roomType);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoomType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoomType', []);

        return parent::getRoomType();
    }

    /**
     * {@inheritDoc}
     */
    public function getHotel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHotel', []);

        return parent::getHotel();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccommodation($accommodation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccommodation', [$accommodation]);

        return parent::setAccommodation($accommodation);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccommodation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccommodation', []);

        return parent::getAccommodation();
    }

    /**
     * {@inheritDoc}
     */
    public function removeAccommodation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAccommodation', []);

        return parent::removeAccommodation();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumber($number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumber', [$number]);

        return parent::setNumber($number);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumber', []);

        return parent::getNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberWithPrefix($numberWithPrefix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberWithPrefix', [$numberWithPrefix]);

        return parent::setNumberWithPrefix($numberWithPrefix);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberWithPrefix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberWithPrefix', []);

        return parent::getNumberWithPrefix();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdults($adults)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdults', [$adults]);

        return parent::setAdults($adults);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdults()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdults', []);

        return parent::getAdults();
    }

    /**
     * {@inheritDoc}
     */
    public function setChildren($children)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChildren', [$children]);

        return parent::setChildren($children);
    }

    /**
     * {@inheritDoc}
     */
    public function getChildren()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChildren', []);

        return parent::getChildren();
    }

    /**
     * {@inheritDoc}
     */
    public function setBegin($begin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBegin', [$begin]);

        return parent::setBegin($begin);
    }

    /**
     * {@inheritDoc}
     */
    public function getBegin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBegin', []);

        return parent::getBegin();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnd($end)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnd', [$end]);

        return parent::setEnd($end);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnd', []);

        return parent::getEnd();
    }

    /**
     * {@inheritDoc}
     */
    public function getPromotion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromotion', []);

        return parent::getPromotion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromotion(\MBH\Bundle\PriceBundle\Document\Promotion $promotion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromotion', [$promotion]);

        return parent::setPromotion($promotion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromotionTotal($calculate = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromotionTotal', [$calculate]);

        return parent::getPromotionTotal($calculate);
    }

    /**
     * {@inheritDoc}
     */
    public function setPromotionTotal($promotionTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromotionTotal', [$promotionTotal]);

        return parent::setPromotionTotal($promotionTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getPackagePrice($discount = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPackagePrice', [$discount]);

        return parent::getPackagePrice($discount);
    }

    /**
     * {@inheritDoc}
     */
    public function setPackagePrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPackagePrice', [$price]);

        return parent::setPackagePrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote($note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', [$note]);

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setPurposeOfArrival($purposeOfArrival)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPurposeOfArrival', [$purposeOfArrival]);

        return parent::setPurposeOfArrival($purposeOfArrival);
    }

    /**
     * {@inheritDoc}
     */
    public function getPurposeOfArrival()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPurposeOfArrival', []);

        return parent::getPurposeOfArrival();
    }

    /**
     * {@inheritDoc}
     */
    public function addTourist(\MBH\Bundle\PackageBundle\Document\Tourist $tourist)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTourist', [$tourist]);

        return parent::addTourist($tourist);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTourist(\MBH\Bundle\PackageBundle\Document\Tourist $tourist)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTourist', [$tourist]);

        return parent::removeTourist($tourist);
    }

    /**
     * {@inheritDoc}
     */
    public function getTourists()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTourists', []);

        return parent::getTourists();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPaid', []);

        return parent::getIsPaid();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaid', []);

        return parent::getPaid();
    }

    /**
     * {@inheritDoc}
     */
    public function getDays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDays', []);

        return parent::getDays();
    }

    /**
     * {@inheritDoc}
     */
    public function getNights()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNights', []);

        return parent::getNights();
    }

    /**
     * {@inheritDoc}
     */
    public function setChannelManagerType($channelManagerType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChannelManagerType', [$channelManagerType]);

        return parent::setChannelManagerType($channelManagerType);
    }

    /**
     * {@inheritDoc}
     */
    public function getChannelManagerType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChannelManagerType', []);

        return parent::getChannelManagerType();
    }

    /**
     * {@inheritDoc}
     */
    public function setChannelManagerId($channelManagerId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChannelManagerId', [$channelManagerId]);

        return parent::setChannelManagerId($channelManagerId);
    }

    /**
     * {@inheritDoc}
     */
    public function getChannelManagerId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChannelManagerId', []);

        return parent::getChannelManagerId();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(bool $accommodation = false, bool $payer = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', [$accommodation, $payer]);

        return parent::getTitle($accommodation, $payer);
    }

    /**
     * {@inheritDoc}
     */
    public function setArrivalTime(\DateTime $arrivalTime = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArrivalTime', [$arrivalTime]);

        return parent::setArrivalTime($arrivalTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrivalTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrivalTime', []);

        return parent::getArrivalTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartureTime(\DateTime $departureTime = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartureTime', [$departureTime]);

        return parent::setDepartureTime($departureTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartureTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartureTime', []);

        return parent::getDepartureTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscount($discount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscount', [$discount]);

        return parent::setDiscount($discount);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscount($percent = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscount', [$percent]);

        return parent::getDiscount($percent);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountMoney()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountMoney', []);

        return parent::getDiscountMoney();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPercentDiscount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPercentDiscount', []);

        return parent::getIsPercentDiscount();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPercentDiscount($isPercentDiscount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPercentDiscount', [$isPercentDiscount]);

        return parent::setIsPercentDiscount($isPercentDiscount);
    }

    /**
     * {@inheritDoc}
     */
    public function addService(\MBH\Bundle\PackageBundle\Document\PackageService $service)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addService', [$service]);

        return parent::addService($service);
    }

    /**
     * {@inheritDoc}
     */
    public function removeService(\MBH\Bundle\PackageBundle\Document\PackageService $service)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeService', [$service]);

        return parent::removeService($service);
    }

    /**
     * {@inheritDoc}
     */
    public function getServices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServices', []);

        return parent::getServices();
    }

    /**
     * {@inheritDoc}
     */
    public function setServicesPrice($servicesPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServicesPrice', [$servicesPrice]);

        return parent::setServicesPrice($servicesPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getServicesPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServicesPrice', []);

        return parent::getServicesPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberWithPayer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberWithPayer', []);

        return parent::getNumberWithPayer();
    }

    /**
     * {@inheritDoc}
     */
    public function getSource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSource', []);

        return parent::getSource();
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmed', []);

        return parent::getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrder(\MBH\Bundle\PackageBundle\Document\Order $order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrder', [$order]);

        return parent::setOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', []);

        return parent::getOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsCheckIn($isCheckIn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsCheckIn', [$isCheckIn]);

        return parent::setIsCheckIn($isCheckIn);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsCheckIn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsCheckIn', []);

        return parent::getIsCheckIn();
    }

    /**
     * {@inheritDoc}
     */
    public function getOneDayPrice($day = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOneDayPrice', [$day]);

        return parent::getOneDayPrice($day);
    }

    /**
     * {@inheritDoc}
     */
    public function isEarlyCheckIn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEarlyCheckIn', []);

        return parent::isEarlyCheckIn();
    }

    /**
     * {@inheritDoc}
     */
    public function isLateCheckOut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isLateCheckOut', []);

        return parent::isLateCheckOut();
    }

    /**
     * {@inheritDoc}
     */
    public function setPricesByDate($pricesByDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPricesByDate', [$pricesByDate]);

        return parent::setPricesByDate($pricesByDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPricesByDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPricesByDate', []);

        return parent::getPricesByDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getPricesByDateByPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPricesByDateByPrice', []);

        return parent::getPricesByDateByPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsSmoking($isSmoking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsSmoking', [$isSmoking]);

        return parent::setIsSmoking($isSmoking);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsSmoking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsSmoking', []);

        return parent::getIsSmoking();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorrupted($corrupted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorrupted', [$corrupted]);

        return parent::setCorrupted($corrupted);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorrupted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorrupted', []);

        return parent::getCorrupted();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalOverwrite($totalOverwrite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalOverwrite', [$totalOverwrite]);

        return parent::setTotalOverwrite($totalOverwrite);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalOverwrite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalOverwrite', []);

        return parent::getTotalOverwrite();
    }

    /**
     * {@inheritDoc}
     */
    public function getService($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getService', [$code]);

        return parent::getService($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getMainTourist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMainTourist', []);

        return parent::getMainTourist();
    }

    /**
     * {@inheritDoc}
     */
    public function getPayer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayer', []);

        return parent::getPayer();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsCheckOut($isCheckOut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsCheckOut', [$isCheckOut]);

        return parent::setIsCheckOut($isCheckOut);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsCheckOut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsCheckOut', []);

        return parent::getIsCheckOut();
    }

    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', []);

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpdate', []);

        return parent::preUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function checkCheckInOut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkCheckInOut', []);

        return parent::checkCheckInOut();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginalPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginalPrice', []);

        return parent::getOriginalPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginalPrice($originalPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginalPrice', [$originalPrice]);

        return parent::setOriginalPrice($originalPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getDebt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDebt', []);

        return parent::getDebt();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaidStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaidStatus', []);

        return parent::getPaidStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsLocked', []);

        return parent::getIsLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsLocked($isLocked)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsLocked', [$isLocked]);

        return parent::setIsLocked($isLocked);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoomStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoomStatus', []);

        return parent::getRoomStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function isDiscountValid(\Symfony\Component\Validator\Context\ExecutionContextInterface $context)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDiscountValid', [$context]);

        return parent::isDiscountValid($context);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrices', []);

        return parent::getPrices();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrices($prices)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrices', [$prices]);

        return parent::setPrices($prices);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsForceBooking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsForceBooking', []);

        return parent::getIsForceBooking();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsForceBooking($isForceBooking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsForceBooking', [$isForceBooking]);

        return parent::setIsForceBooking($isForceBooking);
    }

    /**
     * {@inheritDoc}
     */
    public function clearServices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'clearServices', []);

        return parent::clearServices();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsEnabled', []);

        return parent::getIsEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsEnabled($isEnabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsEnabled', [$isEnabled]);

        return parent::setIsEnabled($isEnabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt(\DateTime $deletedAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', [$deletedAt]);

        return parent::setDeletedAt($deletedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', []);

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function isDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isDeleted', []);

        return parent::isDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy($createdBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$createdBy]);

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedBy($updatedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedBy', [$updatedBy]);

        return parent::setUpdatedBy($updatedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedBy', []);

        return parent::getUpdatedBy();
    }

}
