<?php


namespace Tests\Bundle\SearchBundle\Services;


use MBH\Bundle\BaseBundle\Lib\Test\WebTestCase;
use MBH\Bundle\HotelBundle\Document\Hotel;
use MBH\Bundle\SearchBundle\Services\Calculation;

class CalculationTest extends WebTestCase
{

    /** @var Calculation */
    private $service;

    /** @var \MBH\Bundle\PackageBundle\Services\Calculation */
    private $oldService;

    public function setUp()
    {
        $this->service = $this->getContainer()->get('mbh_search.calculation');
        $this->oldService = $this->getContainer()->get('mbh.calculation');
        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testCalcPrices()
    {
        $dm = $this->getContainer()->get('doctrine_mongodb.odm.default_document_manager');

        /** @var Hotel $hotel */
        $hotel = $dm->getRepository(Hotel::class)->findOneBy([]);
        $roomType = $hotel->getRoomTypes()->first();
        $tariff = $hotel->getTariffs()->first();
        $begin = new \DateTime("midnight");
        $end = new \DateTime("midnight +5 days");
        $adults = 2;
        $children = 1;

        $actual = $this->service->calcPrices($roomType, $tariff, $begin, (clone $end)->modify('-1 day'));
    }

    public function testOldCalcPrices()
    {
        $dm = $this->getContainer()->get('doctrine_mongodb.odm.default_document_manager');

        /** @var Hotel $hotel */
        $hotel = $dm->getRepository(Hotel::class)->findOneBy([]);
        $roomType = $hotel->getRoomTypes()->first();
        $tariff = $hotel->getTariffs()->first();
        $begin = new \DateTime("midnight");
        $end = new \DateTime("midnight +5 days");
        $adults = 2;
        $children = 1;

        $actual = $this->oldService->calcPrices($roomType, $tariff, $begin, (clone $end)->modify('-1 day'));
    }
}