<?php

namespace MBH\Bundle\ChannelManagerBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class OktogoController__JMSInjector
{
    public static function inject($container) {
        $instance = new \MBH\Bundle\ChannelManagerBundle\Controller\OktogoController();
        return $instance;
    }
}
