<?php

namespace MBH\Bundle\WarehouseBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class WarehouseController__JMSInjector
{
    public static function inject($container) {
        $instance = new \MBH\Bundle\WarehouseBundle\Controller\WarehouseController();
        return $instance;
    }
}
