<?php

namespace MBH\Bundle\PackageBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DocumentsController__JMSInjector
{
    public static function inject($container) {
        $instance = new \MBH\Bundle\PackageBundle\Controller\DocumentsController();
        return $instance;
    }
}
