<?php

namespace MBH\Bundle\PriceBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class RoomCacheController__JMSInjector
{
    public static function inject($container) {
        $instance = new \MBH\Bundle\PriceBundle\Controller\RoomCacheController();
        return $instance;
    }
}
