<?php

namespace MBH\Bundle\ClientBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DocumentTemplateController__JMSInjector
{
    public static function inject($container) {
        $instance = new \MBH\Bundle\ClientBundle\Controller\DocumentTemplateController();
        return $instance;
    }
}
