<?php

namespace MBH\Bundle\RestaurantBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class DishOrderController__JMSInjector
{
    public static function inject($container) {
        $instance = new \MBH\Bundle\RestaurantBundle\Controller\DishOrderController();
        return $instance;
    }
}
