<?php


namespace MBH\Bundle\BaseBundle\Form;


use MBH\Bundle\BaseBundle\Document\ProtectedFile;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Image;

class ProtectedFileType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'imageFile',
                FileType::class,
                [
                    'group' => 'no-group',
                    'label' => false,
//                    'constraints' => [
//                        new Image(
//                            [
//                                'minWidth' => 400,
//                                'maxWidth' => 400,
//                                'maxHeight' => 200,
//                                'minHeight' => 200,
//                            ]
//                        ),
//                    ],
                ]
            );
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
        $view->vars['stamp'] = $form->getData();
        $view->vars['parentOwnerId'] = $options['parentOwnerId'];
    }


    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => ProtectedFile::class,
                'parentOwnerId' => null
            ]
        );
    }


}