- name: Apt cache update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Python adding
  apt:
    name: python-minimal
    state: present

- name: ensure python-software-properties is installed
  apt: pkg=python-software-properties state=installed

- name: Install common Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items: "{{ common_packages }}"
  when: common_packages is defined

- name: Apt autoremove
  apt:
    autoremove: yes