services:
    mbh_search.search_query_generator:
        class: MBH\Bundle\SearchBundle\Services\SearchQueryGenerator
        arguments: ['@mbh_search.additional_days_generator' , '@mbh_search.data_holder']

    mbh_search.search_condition_creator:
        class: MBH\Bundle\SearchBundle\Services\SearchConditionsCreator
        arguments: ["@form.factory"]

    mbh_search.additional_days_generator:
        class: MBH\Bundle\SearchBundle\Services\AdditionalDatesGenerator

    mbh_search.restrictions_checker_service:
        class: MBH\Bundle\SearchBundle\Services\RestrictionsCheckerService
        calls:
            - [addChecker, ['@mbh_search.restrictions.on_close']]
            - [addChecker, ['@mbh_search.restrictions.on_close_arrival']]
            - [addChecker, ['@mbh_search.restrictions.on_close_departure']]
            - [addChecker, ['@mbh_search.restrictions.on_max_before_arrival']]
            - [addChecker, ['@mbh_search.restrictions.on_max_guest']]
            - [addChecker, ['@mbh_search.restrictions.on_max_stay']]
            - [addChecker, ['@mbh_search.restrictions.on_max_stay_arrival']]
            - [addChecker, ['@mbh_search.restrictions.on_min_before_arrival']]
            - [addChecker, ['@mbh_search.restrictions.on_min_guest']]
            - [addChecker, ['@mbh_search.restrictions.on_min_stay']]
            - [addChecker, ['@mbh_search.restrictions.on_min_stay_arrival']]

        arguments: ['@mbh_search.data_holder']

    mbh_search.restrictions.on_close:
        public: false
        class: MBH\Bundle\SearchBundle\Lib\Restrictions\Closed

    mbh_search.restrictions.on_close_arrival:
        public: false
        class: MBH\Bundle\SearchBundle\Lib\Restrictions\ClosedOnArrival

    mbh_search.restrictions.on_close_departure:
        public: false
        class: MBH\Bundle\SearchBundle\Lib\Restrictions\ClosedOnDeparture

    mbh_search.restrictions.on_max_before_arrival:
        public: false
        class: MBH\Bundle\SearchBundle\Lib\Restrictions\MaxBeforeArrival

    mbh_search.restrictions.on_max_guest:
        public: false
        class: MBH\Bundle\SearchBundle\Lib\Restrictions\MaxGuest

    mbh_search.restrictions.on_max_stay:
        public: false
        class: MBH\Bundle\SearchBundle\Lib\Restrictions\MaxStay

    mbh_search.restrictions.on_max_stay_arrival:
        public: false
        class: MBH\Bundle\SearchBundle\Lib\Restrictions\MaxStayArrival

    mbh_search.restrictions.on_min_before_arrival:
        public: false
        class: MBH\Bundle\SearchBundle\Lib\Restrictions\MinBeforeArrival

    mbh_search.restrictions.on_min_guest:
        public: false
        class: MBH\Bundle\SearchBundle\Lib\Restrictions\MinGuest

    mbh_search.restrictions.on_min_stay:
        public: false
        class: MBH\Bundle\SearchBundle\Lib\Restrictions\MinStay

    mbh_search.restrictions.on_min_stay_arrival:
        public: false
        class: MBH\Bundle\SearchBundle\Lib\Restrictions\MinStayArrival

    #search
    mbh_search.searcher:
        class: MBH\Bundle\SearchBundle\Services\Search\Searcher
        arguments: ['@mbh_search.restrictions_checker_service', '@mbh_search.search_limit_checker', '@mbh_search.result_composer', '@validator', '@mbh_search.data_holder']

    mbh_search.search_limit_checker:
        class: MBH\Bundle\SearchBundle\Services\Search\SearchLimitChecker
        arguments: ['@mbh_search.client_config_repository', '@doctrine.odm.mongodb.document_manager', '@mbh_search.data_holder']

    mbh_search.room_type_repository:
        class: MBH\Bundle\HotelBundle\Document\RoomTypeRepository
        factory: ["@doctrine.odm.mongodb.document_manager", getRepository]
        arguments:
            - MBH\Bundle\HotelBundle\Document\RoomType

    mbh_search.room_cache_repository:
        class: MBH\Bundle\PriceBundle\Document\RoomCacheRepository
        factory: ["@doctrine.odm.mongodb.document_manager", getRepository]
        arguments:
            - MBH\Bundle\PriceBundle\Document\RoomCache

    mbh_search.price_cache_repository:
        class: MBH\Bundle\PriceBundle\Document\PriceCacheRepository
        factory: ["@doctrine.odm.mongodb.document_manager", getRepository]
        arguments:
            - MBH\Bundle\PriceBundle\Document\PriceCache

    mbh_search.tariff_repository:
        class: MBH\Bundle\PriceBundle\Document\TariffRepository
        factory: ["@doctrine.odm.mongodb.document_manager", getRepository]
        arguments:
            - MBH\Bundle\PriceBundle\Document\Tariff

    mbh_search.client_config_repository:
        class: MBH\Bundle\ClientBundle\Document\ClientConfigRepository
        factory: ["@doctrine.odm.mongodb.document_manager", getRepository]
        arguments:
            - MBH\Bundle\ClientBundle\Document\ClientConfig

    mbh_search.restriction_repository:
        class: MBH\Bundle\PriceBundle\Document\RestrictionRepository
        factory: ["@doctrine.odm.mongodb.document_manager", getRepository]
        arguments:
            - MBH\Bundle\PriceBundle\Document\Restriction

    mbh_search.room_repository:
        class: MBH\Bundle\HotelBundle\Document\RoomRepository
        factory: ["@doctrine.odm.mongodb.document_manager", getRepository]
        arguments:
            - MBH\Bundle\HotelBundle\Document\Room

    mbh_search.package_accommodation_repository:
        class: MBH\Bundle\PackageBundle\Document\PackageAccommodationRepository
        factory: ["@doctrine.odm.mongodb.document_manager", getRepository]
        arguments:
            - MBH\Bundle\PackageBundle\Document\PackageAccommodation

    mbh_search.search_conditions_repository:
        class: MBH\Bundle\SearchBundle\Document\SearchConditionsRepository
        factory: ["@doctrine.odm.mongodb.document_manager", getRepository]
        arguments:
            - MBH\Bundle\SearchBundle\Document\SearchConditions

# Для теста - калькуляции - брал текущую.
#    mbh_search.result_composer:
#        class: MBH\Bundle\SearchBundle\Services\Search\SearchResultComposer
#        arguments: ['@doctrine.odm.mongodb.document_manager', '@mbh.hotel.room_type_manager', '@mbh.calculation']

    mbh_search.result_composer:
        class: MBH\Bundle\SearchBundle\Services\Search\SearchResultComposer
        arguments: ['@mbh.hotel.room_type_manager', '@mbh_search.calculation', '@mbh_search.data_holder', '@mbh_search.search_limit_checker']

    mbh_search.calculation:
        class: MBH\Bundle\SearchBundle\Services\Calc\Calculation
        arguments: ['@mbh_search.price_caches_merger', '@mbh_search.data_holder']

    mbh_search.price_caches_merger:
        class: MBH\Bundle\SearchBundle\Services\Calc\PriceCachesMerger
        arguments: ['@mbh_search.tariff_repository', '@mbh_search.data_holder']

    mbh_search.data_holder:
        class: MBH\Bundle\SearchBundle\Lib\DataHolder
        arguments: ['@mbh_search.tariff_repository', '@mbh_search.room_type_repository', '@mbh_search.restriction_repository', '@mbh_search.client_config_repository', '@mbh_search.room_cache_repository', '@mbh_search.room_repository', '@mbh_search.package_accommodation_repository', '@mbh_search.price_cache_repository', '@mbh_search.search_conditions_repository']

    mbh_search.search_conditions_type:
        class: MBH\Bundle\SearchBundle\Form\SearchConditionsType
        arguments: ['@mbh_search.client_config_repository']
        tags:
            - { name: form.type, alias: MBH\Bundle\SearchBundle\Form\SearchConditionsType }

    mbh_search.search:
        class: MBH\Bundle\SearchBundle\Services\Search\Search
        arguments: ['@mbh_search.restrictions_checker_service', '@mbh_search.searcher', '@doctrine.odm.mongodb.document_manager', '@mbh_search.search_condition_creator', '@mbh_search.search_query_generator', '@serializer']