services:
    mbh_search.search_query_generator:
        class: MBH\Bundle\SearchBundle\Services\SearchQueryGenerator
        arguments: ['@doctrine.odm.mongodb.document_manager', '@mbh_search.additional_days_generator']

    mbh_search.search_request_receiver:
        class: MBH\Bundle\SearchBundle\Services\SearchRequestReceiver
        arguments: ["@form.factory"]

    mbh_search.additional_days_generator:
        class: MBH\Bundle\SearchBundle\Services\AdditionalDatesGenerator

    mbh_search.restrictions_checker_service:
        class: MBH\Bundle\SearchBundle\Services\RestrictionsCheckerService
        calls:
            - [addChecker, ['@mbh_search.restrictions.on_close']]
        arguments: ['@doctrine.odm.mongodb.document_manager']

    mbh_search.restrictions.on_close:
        public: false
        class: MBH\Bundle\SearchBundle\Lib\Restrictions\OnClose