<?php


namespace MBH\Bundle\SearchBundle\Lib;


use Symfony\Bridge\Doctrine\Form\ChoiceList\DoctrineChoiceLoader;

class RoomTypesFormChoiceLoader extends DoctrineChoiceLoader
{
    public function loadChoiceList($value = null)
    {
        return parent::loadChoiceList($value); // TODO: Change the autogenerated stub
    }

    public function loadValuesForChoices(array $choices, $value = null)
    {
        return parent::loadValuesForChoices($choices, $value); // TODO: Change the autogenerated stub
    }

    public function loadChoicesForValues(array $values, $value = null)
    {
        return parent::loadChoicesForValues($values, $value); // TODO: Change the autogenerated stub
    }

}